### ISSUE TITLE
Can’t find Design WG (Giveth) 

### ISSUE THREAD

**Issue by freshelle** [GeneralMagicio/companybrain#29]
For Lulu, I can’t find Design WG (Giveth) in Member > Admin so I can edit it. Works already updated

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/86718721/229234474-4b05b6c1-b2a4-4203-9cab-1e504e366ac0.png">
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/86718721/229234553-e72c855b-0be9-464f-9558-f82dcc6841c2.png">

**Comment by tomislavmamic** [comment]
Fixed it, what was missing was adding in Admin doc, a business access for Giveth to Lulu. Here:
![CleanShot 2023-04-01 at 11 04 50@2x](https://user-images.githubusercontent.com/15949483/229276789-128727d2-19ba-4e06-afbb-d413c2c54076.png)


However, I didn't add it now, so you can do it. What I did do, is made it so that if member has business access, or if they are listed in members for that work. Like what you updated for Lulu there. Check now.
![CleanShot 2023-04-01 at 11 07 39@2x](https://user-images.githubusercontent.com/15949483/229276957-f091a4a2-a287-4a46-aef0-db024a7bced8.png)

**Comment by tomislavmamic** [comment]
Here you can see that Lulu doesn't have business access for Giveth. We use this to filter which organisation details (members, projects, etc...) in Members doc can a member see. By default, if you are not member of GM you don't see GM things, and if you are not member of Giveth, you don't see Giveth things there.

Please check if that column is updated so that people can see what they need to see.

<img width="1454" alt="CleanShot 2023-04-01 at 11 08 51@2x" src="https://user-images.githubusercontent.com/15949483/229277017-11f58f67-0533-4f29-aec2-4d511910d8be.png">

**Comment by freshelle** [comment]
Ok thanks.. so we have to update 2 docs.
1. Works
2. Members > business access
